apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-request-handler-deploy
  namespace: decidim-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-request-handler
  template:
    metadata:
      labels:
        app: ai-request-handler
    spec:
      containers:
      - name: ai-request-handler
        image: rg.fr-par.scw.cloud/decidim-ai/ai_request_handler:v1.0.9
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "1"
            memory: "256Mi"
          limits:
            memory: "512Mi"
        env:
          - name: GRIST_DOC_ID
            valueFrom:
              secretKeyRef:
                name: arh-secrets
                key: GRIST_DOC_ID
          - name: GRIST_API_KEY
            valueFrom:
              secretKeyRef:
                name: arh-secrets
                key: GRIST_API_KEY
          - name: GRIST_SERVER
            valueFrom:
              secretKeyRef:
                name: arh-secrets
                key: GRIST_SERVER
          - name: PG_DSN
            valueFrom:
              secretKeyRef:
                name: arh-secrets
                key: PG_DSN
          - name: CLOUD_BASE_URL
            valueFrom:
              secretKeyRef:
                name: arh-secrets
                key: CLOUD_BASE_URL
          - name: CLOUD_API_KEY
            valueFrom:
              secretKeyRef:
                name: arh-secrets
                key: CLOUD_API_KEY
          - name: WEBHOOK_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: arh-secrets
                key: WEBHOOK_ENDPOINT
          - name: WEBHOOK_AUTH_NAME
            valueFrom:
              secretKeyRef:
                name: arh-secrets
                key: WEBHOOK_AUTH_NAME
          - name: WEBHOOK_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: arh-secrets
                key: WEBHOOK_AUTH_TOKEN
          - name: SPAM_PERIOD_LIMIT
            valueFrom:
              secretKeyRef:
                name: arh-secrets
                key: SPAM_PERIOD_LIMIT
          - name: SPAM_LIMIT
            valueFrom:
              secretKeyRef:
                name: arh-secrets
                key: SPAM_LIMIT
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: ai-request-handler--re.redis.libre.sh
                key: host
          - name: REDIS_PORT
            valueFrom:
              secretKeyRef:
                name: ai-request-handler--re.redis.libre.sh
                key: port
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ai-request-handler--re.redis.libre.sh
                key: password