---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ai_request_handler
  namespace: decidim-ai
spec:
  interval: 60m0s
  ref:
    branch: main
  url: https://github.com/OpenSourcePolitics/ai_request_handler
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ai_request_handler
  namespace: decidim-ai
spec:
  prune: true
  interval: 10m0s
  path: ./gitops
  sourceRef:
    kind: GitRepository
    name: ai_request_handler
