---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ai-request-handler
  namespace: decidim-ai
spec:
  interval: 01m0s
  ref:
    branch: main
  url: https://github.com/OpenSourcePolitics/ai_request_handler
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ai-request-handler
  namespace: decidim-ai
spec:
  prune: true
  interval: 01m0s
  path: ./gitops
  images:
    - name: rg.fr-par.scw.cloud/decidim-ai/ai_request_handler
      newTag: 0.0.1
resources:
  - deployment.yaml