apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: ai-request-handler-kus
  namespace: decidim-ai
resources:
  - flux-sync.yaml
  - deployment.yaml
  - secret.yaml
  - service.yaml