apiVersion: v1
kind: Service
metadata:
  name: ai-request-handler-svc
  namespace: decidim-ai
spec:
  selector:
    app: ai-request-handler
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80