apiVersion: v1
kind: Service
metadata:
  name: ai-request-handler
  namespace: decidim-ai
spec:
  selector:
    app: ai-request-handler
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 80