apiVersion: v1
kind: Service
metadata:
  name: ai_request_handler
  namespace: decidim-ai
spec:
  selector:
    app: ai_request_handler
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80