name: Docker image build and push

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  generate_release:
    name: Generate release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: OpenSourcePolitics/build-and-push-images-action@master
        with:
          registry: ${{ vars.REGISTRY_ENDPOINT }}
          namespace: ${{ vars.REGISTRY_NAMESPACE }}
          password: ${{ secrets.TOKEN }}
          image_name: ${{ vars.IMAGE_NAME }}
          tag: ${{ github.ref_name }}
          context: "./app"
